// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import ClassToggleController from "./class_toggle_controller.js"
application.register("class-toggle", ClassToggleController)

import ElementController from "./element_controller.js"
application.register("element", ElementController)

import TransitionController from "./transition_controller.js"
application.register("transition", TransitionController)
