// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import ClassToggleController from "./class_toggle_controller"
application.register("class-toggle", ClassToggleController)

import ClickTransitionController from "./click_transition_controller"
application.register("click-transition", ClickTransitionController)

import ElementController from "./element_controller"
application.register("element", ElementController)

import RevealController from "./reveal_controller"
application.register("reveal", RevealController)

import TransitionController from "./transition_controller"
application.register("transition", TransitionController)
