inherit_from:
  - node_modules/@prettier/plugin-ruby/rubocop.yml
require:
  - rubocop-rails
  - rubocop-performance
  - rubocop-rspec
AllCops:
  NewCops: enable
Style/Documentation:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Metrics/BlockLength:
  Exclude:
    - "config/environments/*.rb"
    - "spec/**/*.rb"
    - "db/seeds.rb"
Metrics/MethodLength:
  Exclude:
    - "db/migrate/*.rb"
Layout/LineLength:
  Exclude:
    - "config/initializers/*.rb"
    - "db/migrate/*.rb"
    - "db/seeds.rb"
Style/StringLiterals:
  Exclude:
    - "db/migrate/*.rb"
Lint/MissingSuper:
  Exclude:
    - "app/components/**/*.rb"